name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Set Git config
        run: |
          git config user.email "serg1557733@ukr.net"
          git config user.name "serhii borshch"

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Set up GitHub Pages branch
        run: git checkout --orphan gh-pages

      - name: Deploy to GitHub Pages
        run: npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
